server:
  port: 9009

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 10
  datasource:
        url: jdbc:mysql://localhost:3306/banma_dev?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMultiQueries=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver